docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
site_name: laminas-skeleton-installer
site_description: 'Skeleton Installer: Composer plugin for initial LaminasSkeletonApplication installation'
repo_url: 'https://github.com/laminas/laminas-skeleton-installer'
